[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
ctor = "0.6.2"
env_logger = "0.11.8"
euclid = "0.22.11"
log = "0.4.28"
nom = "8.0.0"
strum = "0.27.2"
strum_macros = "0.27.2"
